name: Build and test

on:
  push:
    branches: ['*']

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Docker test containers
        run: |
          docker compose up mysql pg -d
          sleep 5

      - name: Run Tests
        run: npm test

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: ./coverage/lcov.info

      - name: Build
        run: |
          npm install @sqltags/core@latest --workspace=drivers
          npm run build --workspaces
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
