name: Build, test and publish

on:
  push:
    tags: ['v*']

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Docker test containers
        run: |
          docker compose up mysql pg -d
          sleep 5

      - name: Run Tests
        run: npm test

      - name: Publish
        run: npm run publish-all
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
