name: Build and test

on:
  push:
    branches: ['*']

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Docker test containers
        run: |
          docker compose up mysql pg -d
          sleep 5

      - name: Run Tests
        run: npm test
