name: Build, test and publish

on:
  push:
    tags: ['**/v*']

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate branch name
        run: |
          REF="${{ github.ref_name }}"
          PACKAGE="${REF%/*}"
          # package name must exist as directory
          if [ ! -d "./$PACKAGE" ]; then
            echo "Invalid branch name: $PACKAGE"
            exit 1
          fi

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Docker test containers
        run: |
          docker compose up mysql pg -d
          sleep 5

      - name: Run Tests
        run: npm test

      - name: Publish
        run: |
          REF="${{ github.ref_name }}"
          PACKAGE="${REF%/*}"
          cd ./$PACKAGE && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
